# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

omitNaCpp <- function(x) {
    .Call('_perturbLM_omitNaCpp', PACKAGE = 'perturbLM', x)
}

sortCpp <- function(v) {
    .Call('_perturbLM_sortCpp', PACKAGE = 'perturbLM', v)
}

calcPvalLessCpp <- function(v, x) {
    .Call('_perturbLM_calcPvalLessCpp', PACKAGE = 'perturbLM', v, x)
}

calcPvalGreaterCpp <- function(v, x) {
    .Call('_perturbLM_calcPvalGreaterCpp', PACKAGE = 'perturbLM', v, x)
}

winsorizeMatrix <- function(Mat, Trim) {
    .Call('_perturbLM_winsorizeMatrix', PACKAGE = 'perturbLM', Mat, Trim)
}

